### ISSUE TITLE
tag release 1.0.2 and push to pip to fix isAlive() for Python 3.9 Users

### ISSUE THREAD

**Issue by bernhardkaindl** [Tanganelli/CoAPthon3#44]
Ubuntu 21.04 and likely other distros now use Python-3.9.

It removed the long-deprecated isAlive() which was fixed in git this March.

Please make this and the other fixes in git available on pip by tagging release 1.0.2
and pushing it to pip like you did in 2018 for version 1.0.1.

Thanks a ton ;-)

**Comment by warner83** [comment]
A new version is now on pip.
