### ISSUE TITLE
Coapthon log handling is not friendly to integration

### ISSUE THREAD

**Issue by jackjansen** [Tanganelli/CoAPthon3#9]
Coapthons way of using the Python logging module isn't great if you're integrating it into a larger package.

Importing any of the coapthon modules seems to override any logger settings, and not only for, say, logger `coapthon.client.coap` but also for the root logger and more.

In addition, a file "logging.conf" is always created in the current directory.

All of this wreaks havoc with my carefully setup logging structure, and there is no way I can event monkeypatch it (by overriding `coapthon.utils.create_logging()`) because the references to the logging.conf file are all over the place.

**Comment by Tanganelli** [comment]
Maybe you are right, feel free to perform any modification you like and
then commit them.

Il giorno sab 10 nov 2018 alle ore 18:08 Jack Jansen <
notifications@github.com> ha scritto:

**Comment by jackjansen** [comment]
When I prepared for doing this I noticed that someone has already fixed this, 94aa766b8f seems to have all the fixes. So I guess my problem is really that there hasn't been a new release to PyPi with that fix. Can I ask that you do a new release?

**Comment by Tanganelli** [comment]
I have some ongoing work before the release, however you can easily install
the github version with pip if this is the issue.


Il giorno lun 12 nov 2018 alle ore 13:21 Jack Jansen <
notifications@github.com> ha scritto:

**Comment by jackjansen** [comment]
Ok, thanks!
